// This program will have the user try to guess a pseudo random number generated by the computer in 7 tries or less. 
// Initialize global variables
var user_guess;
var attempts = 1;
var counter = 7;
function secret () {
  var comp_num = Math.floor(Math.random()*100)+1;
  var name = prompt("Type in your name to play!");

  // Empty prompt
  while (name === '') {
    alert("Gotta enter your name to play. Try again!")
    name = prompt("Type in your name to play!");
  }

  //Show computer number until program is complete
  console.log(comp_num);

  // Do-while loop
  do {
    //Account for entering a string
    user_guess = prompt(name + ", choose a number between 1 and 100. You have " + counter +  " tries to guess the number!");
    while (isNaN(user_guess)) {
      alert("Da Fuq? You call that a number??")
      user_guess = prompt(name + " , choose a number between 1 and 100. You have " + counter +  " tries to guess the number!");
    }

    //Account for empty guess/prompt
    while (user_guess === '') {
      alert('Please type a number to play! You still have ' + counter + ' turns left.')
      user_guess = prompt(name + " , choose a number between 1 and 100. You have " + counter +  " tries to guess the number!");
    }

    attempts += 1;
    counter -= 1;
    if (user_guess > comp_num) {
    alert("Your guess was too high! You have " + counter + " tries left!");
  } else if (user_guess < comp_num) {
    alert("Your guess was too low...You have " + counter + " tries left!");
  } else if (parseInt(user_guess) === comp_num) {
    alert("Congrats, " + name + "! You guessed the computer's number!");
    if (counter >=1) {
      alert("You finished the game with " + counter + " tries left!");

    } else {
      alert("You guessed the number on your last try!");
    }
  }
} while (user_guess != comp_num && (attempts <= 7)) //this will run the above code until this while condition becomes false. When the user picks a number that isn't the same as the computer number, the while condition is true, thereby running the loop again.
  counter = 7;
  // secret();
  var replay = prompt('Do you want to try again??');
  switch (replay.toLowerCase()) {
    case 'y':
    case 'yes':
    case 'sure':
    case 'yeah':
    case 'ok':
    case '1':
    secret();
    break;
    default:
    alert("Thank you for playing!!!");
  }
}
